# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recorder-app/proto/sensor_record.proto
# Protobuf Python Version: 6.33.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '-rc2',
    'recorder-app/proto/sensor_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&recorder-app/proto/sensor_record.proto\x12\tsensorrec\"\x9d\x01\n\x06Header\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.sensorrec.Header.Type\x12\x17\n\x0ftimestamp_nanos\x18\x02 \x01(\x03\"T\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08LOCATION\x10\x01\x12\x08\n\x04NMEA\x10\x02\x12\t\n\x05\x41\x43\x43\x45L\x10\x03\x12\x08\n\x04GYRO\x10\x04\x12\x07\n\x03MAG\x10\x05\x12\t\n\x05OTHER\x10\x06\"\x93\x01\n\x0eLocationRecord\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x06 \x01(\x02\x12\x18\n\x10wallclock_millis\x18\x07 \x01(\x03\"\x1a\n\nNmeaRecord\x12\x0c\n\x04nmea\x18\x01 \x01(\t\"-\n\nSensorVec3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\\\n\x0cSensorRecord\x12%\n\x06values\x18\x01 \x03(\x0b\x32\x15.sensorrec.SensorVec3\x12\x13\n\x0bsensor_type\x18\x02 \x01(\x05\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x05\"\xb6\x01\n\x05\x46rame\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.sensorrec.Header\x12-\n\x08location\x18\x02 \x01(\x0b\x32\x19.sensorrec.LocationRecordH\x00\x12%\n\x04nmea\x18\x03 \x01(\x0b\x32\x15.sensorrec.NmeaRecordH\x00\x12)\n\x06sensor\x18\x04 \x01(\x0b\x32\x17.sensorrec.SensorRecordH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recorder_app.proto.sensor_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=54
  _globals['_HEADER']._serialized_end=211
  _globals['_HEADER_TYPE']._serialized_start=127
  _globals['_HEADER_TYPE']._serialized_end=211
  _globals['_LOCATIONRECORD']._serialized_start=214
  _globals['_LOCATIONRECORD']._serialized_end=361
  _globals['_NMEARECORD']._serialized_start=363
  _globals['_NMEARECORD']._serialized_end=389
  _globals['_SENSORVEC3']._serialized_start=391
  _globals['_SENSORVEC3']._serialized_end=436
  _globals['_SENSORRECORD']._serialized_start=438
  _globals['_SENSORRECORD']._serialized_end=530
  _globals['_FRAME']._serialized_start=533
  _globals['_FRAME']._serialized_end=715
# @@protoc_insertion_point(module_scope)
